### ISSUE TITLE
Conceptual Framework copy-edit checklist

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#19]
## Copy Edit Checklist

As a final step prior to submission, please check off each step. 

**Pro tip:** first come first serve for choosing your favorite task(s)! 

### Tasks

* [x] Check consistency in style (font, headings, spacing)
* [x] Check consistency in style (figures, tables)
* [x] Figure and table captions, legends, labels are correct
* [x] Glossary ('defined terms') is complete 
* [x] References properly formatted and cited
* [ ] Acronyms defined at first use
* [ ] Check for consistent use of defined terms, acronyms, units, chemical symbols 
* [x] Check alignment of tables with text
* [x] Check accessibility (tables, figs, headings)
* [ ] Enumerate formatting conventions; see SDA papers  

### Additional Notes

Document any issues that arise during here, open a new issue, or use ALL CAPS and emojis in Slack.

**Comment by infotroph** [comment]
glossary: deleted
