### ISSUE TITLE
Monitoring report copy-edit checklist

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#32]
## Copy Edit Checklist

As a final step prior to submission, please check off each step. 

**Pro tip:** first come first serve for choosing your favorite task(s)! 

### Tasks

* [ ] Check consistency in style (font, headings, spacing)
* [ ] Check consistency in style (figures, tables)
* [ ] Figure and table captions, legends, labels are correct
* [ ] Glossary ('defined terms') is complete 
* [ ] References properly formatted and cited
* [ ] Acronyms defined at first use
* [ ] Check for consistent use of defined terms, acronyms, units, chemical symbols 

### Additional Notes

Document any issues that arise during here, open a new issue, or use ALL CAPS and emojis in Slack.
