### ISSUE TITLE
Define SIPNET: structure, inputs, outputs, states

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#4]
**Description**

Specify structure and implementation tools of simplified biogeochemistry model for California croplands, including equations to be used and required inputs, outputs, parameters and states.

* [ ] Document existing functionality
* [ ] Develop proposed functionality

Working draft is in https://github.com/ccmmf/modeling_framework/tree/main/sipnet-model-description

**tasks**

* [ ] review proposal and associated literature
* [ ] review existing codebase
* [ ] #11
* [ ] summarize existing code flow (high level) 
* [ ] document additions to workflow (where new equations go)
* [ ] testing approach: assure essential functionality, maybe focused at level of compiled model (vs. fn) behavior. 

- Start with two pools: SOM + litter
- N fixation limited to n-fixing plants

**additional information**
[Proposal](https://docs.google.com/document/d/1Vv5wP-UGOcbFTZ6XeYkkC9xOz3s5W9VprDI-SDdUsCU/edit?usp=sharing)
* Cheng, K. et al. (2013) ‘Predicting methanogenesis from rice paddies using the DAYCENT ecosystem model’, Ecological modelling, 261-262, pp. 19–31. Available at: http://dx.doi.org/10.1016/j.ecolmodel.2013.04.003
* Tang, Y. et al. (2024) ‘Quantifying greenhouse gas emissions in agricultural systems: a comparative analysis of process models’, Ecological modelling, 490(110646), p. 110646. Available at: https://doi.org/10.1016/j.ecolmodel.2024.110646.
{need list of appropriate literature}

[sipnet codebase](https://github.com/PecanProject/sipnet)

**Comment by dlebauer** [comment]
- start with separate litter and bulk SOM (not 3 pools)
- separate NH4 and NO3 pools
- N fixation limited to legumes
