### ISSUE TITLE
Document Model Implementation

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#45]
**Description**

Write documentation for the model implementation, including step-by-step 'quick start' instructions. This will facilitate evaluation and use for new users.

Audience:
- CARB staff users
- Other users
- Contributors

**tasks**

* [x] Table of Parameters
* [x] Document new features including equations
* [x] New format for management events
* [x] 'Quick Start' instructions
* [x] More detailed introduction to use

**References**

Modeling framework should provide a solid first draft.

See also:
- Braswell et al 2005 
- Zobitz et al 2008
- github.com/pecanproject/sipnet documentation folder
