### ISSUE TITLE
2.3.4: Prepare Datasets for Model Initial Conditions and Drivers

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#46]
**Description**

Collect and preprocess datasets needed for initializing and running SIPNET, including weather data, remote sensing data, soil characteristics, and crop management practices for California croplands.

- [ ] add details, datasets, and keep the  [CCMMF Data Needs spreadsheet](https://docs.google.com/spreadsheets/d/1lTLbAN2JhxfLtad9jUTJjFH7OhTLmp-GOVmh86SqkUM/edit?gid=0#gid=0) up to date - it is the 'source of truth'.
- [ ] Document any new formats including the SIPNET event input file 
- [ ] Download datasets or ensure PEcAn download functions work
- [ ] Convert inputs to SIPNET specific formats 

**References**

[CCMMF Data Needs spreadsheet](https://docs.google.com/spreadsheets/d/1lTLbAN2JhxfLtad9jUTJjFH7OhTLmp-GOVmh86SqkUM/edit?gid=0#gid=0)

Table 4 from Conceptual Framework SIPNET Data Requirements

| Value | Source | Spatial scale | Temporal scale | Purpose |
| :---- | :---- | :---- | :---- | :---- |
| Historical meteorological data | Cal-Adapt (Thomas et al. 2018\) | 3 km | daily | Model driver, with ensemble based uncertainty, Stratified grid sampling |
| Fine-temporal resolution historical meteorological data | ERA5 (Hersbach et al. 2020\) | 0.25° | hourly | Temporal downscaling of Cal-Adapt |
| Meteorological drivers through 2100 | Cal-Adapt (Thomas, N., Mukhtyar, S., Galey, B., and Kelly, M. 2018\) | 3 km | hourly | Model driver for future scenarios |
| Soil hydrological parameters | gSSURGO (Ramcharan et al. 2018; Soil Survey Staff 2023\) | 30 m | invariant | Model initial conditions, Stratified grid sampling |
| Soil baseline SOC | SoilGrids (Poggio et al. 2021\) | 250 m | invariant | Model initial conditions, stratified grid sampling |
| Crop identity | DWR statewide crop mapping (CA Dept Water Resources) | vector | annual | Model initial conditions, Stratified grid sampling. |
|  | Cropland Data Layer [(USDA NAS](https://paperpile.com/c/Cs23m1/x0AfT)S [2024\)](https://paperpile.com/c/Cs23m1/x0AfT) | 30 m |  |  |
| Land cover | Landfire (https://www.landfire.gov/) | 30m | Annual for select years | Land cover change |
| Leaf Area Index | MODIS (Knyazikhin et al. 1998\) | 500 m | 4 day | Validate plant growth \+ biomass |
| Evapotranspiration | openET [(Melton et al. 2022\)](https://paperpile.com/c/Cs23m1/unIJ0) | 30 m | daily | Irrigation monitoring |
|  | ECOSTRESS (Fisher et al. 2020\) | 70 m | \~weekly |  |
| Soil moisture | SMAP (Reichle et al. 2019, 2021\) | 9 km | daily | Constrains GHG production \+ irrigation monitoring |
