### ISSUE TITLE
2.3.5: Initial Deployment of Infrastructure for model setup including ingestion / conversion of input data and model execution

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#47]
**Description**

Set up infrastructure to support data ingestion and model execution, including deploying OpenStack, building automated data pipelines, and conducting test deployments using remote sensing data for California croplands.

note: this is **initial deployment** focused on data ingestion and SIPNET execution

**tasks**

* [ ] Document available computing resources (w/ CARB staff)
* [ ] Document user requirements for data ingestion and model execution
* [ ] Set up PEcAn data ingestion and conversion pipelines
* [ ] Set up model execution environment
* [ ] Initial Continuous Integration and Deployment (CI/CD) framework including data ingestion, model execution, and deployment
* [ ] Document set up procedures and configuration

**additional information**

**Comment by dlebauer** [comment]
@hdpriest-ui could you please update status of this? Is it complete?
