### ISSUE TITLE
2.3.6: Write Progress Report 1 (Deliverable)

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#48]
**Description**

Write first progress report detailing the implementation of GHG extensions, testing, and dataset preparation. 

The report should summarize completed work, present testing results, and outline next steps.

"Completed work" section is expected to directly copy and / or reference documentation produced during completion of other tasks. In such cases, work can prioritize improving documentation at its source that will be copied to the report.

**tasks**

* [ ] Model development
* [ ] Report on testing results
* [ ] Describe dataset preparation
* [ ] Infrastructure deployment
* [ ] Next steps and future improvements
* [ ] Internal review
* [ ] Finalize report
* [ ] Submit report

**additional information**

**Comment by dlebauer** [comment]
Progress report submitted focused on Phases 1&2
