### ISSUE TITLE
Define infrastructure for development and testing

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#6]
**Description**

**tasks**

* [ ] Meet w/ CARB IT to discuss: hardware, architecture, environment, access
* [ ] Document available CARB resources
* [ ] Define an approach to development, testing, deployment
  * at what point in the project should we start testing on CARB resources? How much development and testing should / could happen on CARB vs. at NCSA? 
* [ ] Write up section for Conceptual Framework #7 

**additional information**
