### ISSUE TITLE
Write draft Conceptual Framework report and submit for review by CARB.

### ISSUE THREAD

**Issue by dlebauer** [ccmmf/organization#7]
**tasks**

* [ ] #9
* [x] depends on: 
  * #3 
  * #4 
  * #5
* [x] figure out what report should contain (ask team, CARB) 
* [x] wait for dependent issues to be done
* [x] write the report

**additional information**

**Comment by dlebauer** [comment]
Submitted on time, Aug 30; 

created copy of submitted version https://docs.google.com/document/d/14PS6abUv5KPZqEQvl242iX31IWxOgCkEQAweRTMFO8U
